//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEase.IoDrive.Modicon.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlEase.IoDrive.Modicon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Address: 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CommFormat: 的本地化字符串。
        /// </summary>
        internal static string CommFormat {
            get {
                return ResourceManager.GetString("CommFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length only support:2,4 的本地化字符串。
        /// </summary>
        internal static string DoubleLengthError {
            get {
                return ResourceManager.GetString("DoubleLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pass the CRC check 的本地化字符串。
        /// </summary>
        internal static string ErrCheck {
            get {
                return ResourceManager.GetString("ErrCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device returns an abnormal frame，Code error 的本地化字符串。
        /// </summary>
        internal static string Error_Code {
            get {
                return ResourceManager.GetString("Error_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No pass the Parse 的本地化字符串。
        /// </summary>
        internal static string ErrParse {
            get {
                return ResourceManager.GetString("ErrParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RegisterError 的本地化字符串。
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap: 的本地化字符串。
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StarAddr Error :&gt;=0 的本地化字符串。
        /// </summary>
        internal static string ValidateIndexError {
            get {
                return ResourceManager.GetString("ValidateIndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length only support: 1,2,4 的本地化字符串。
        /// </summary>
        internal static string ValidateLengthError {
            get {
                return ResourceManager.GetString("ValidateLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length only support: 1-128 的本地化字符串。
        /// </summary>
        internal static string ValidateStringError {
            get {
                return ResourceManager.GetString("ValidateStringError", resourceCulture);
            }
        }
    }
}
