//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEase.Inspec.DaHeng.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlEase.Inspec.DaHeng.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AcquisitionMode 的本地化字符串。
        /// </summary>
        internal static string AcquisitionMode {
            get {
                return ResourceManager.GetString("AcquisitionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AcquisitionMode：Continuous/SoftTrigger/ExternalTrigger 的本地化字符串。
        /// </summary>
        internal static string AcquisitionMode_Description {
            get {
                return ResourceManager.GetString("AcquisitionMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribute 的本地化字符串。
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoWhite 的本地化字符串。
        /// </summary>
        internal static string AutoWhite {
            get {
                return ResourceManager.GetString("AutoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AutoWhite 的本地化字符串。
        /// </summary>
        internal static string AutoWhite_Description {
            get {
                return ResourceManager.GetString("AutoWhite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BalanceRatio 的本地化字符串。
        /// </summary>
        internal static string BalanceRatio {
            get {
                return ResourceManager.GetString("BalanceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BalanceRatio 的本地化字符串。
        /// </summary>
        internal static string BalanceRatio_Description {
            get {
                return ResourceManager.GetString("BalanceRatio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMPName 的本地化字符串。
        /// </summary>
        internal static string BMPName {
            get {
                return ResourceManager.GetString("BMPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BMPName 的本地化字符串。
        /// </summary>
        internal static string BMPName_Description {
            get {
                return ResourceManager.GetString("BMPName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExposureTime 的本地化字符串。
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExposureTime 的本地化字符串。
        /// </summary>
        internal static string ExposureTime_Description {
            get {
                return ResourceManager.GetString("ExposureTime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gain 的本地化字符串。
        /// </summary>
        internal static string Gain {
            get {
                return ResourceManager.GetString("Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gain 的本地化字符串。
        /// </summary>
        internal static string Gain_Description {
            get {
                return ResourceManager.GetString("Gain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RatioSelector 的本地化字符串。
        /// </summary>
        internal static string RatioSelector {
            get {
                return ResourceManager.GetString("RatioSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RatioSelector 的本地化字符串。
        /// </summary>
        internal static string RatioSelector_Description {
            get {
                return ResourceManager.GetString("RatioSelector_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveBMP 的本地化字符串。
        /// </summary>
        internal static string SaveBMP {
            get {
                return ResourceManager.GetString("SaveBMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as  BMP image 的本地化字符串。
        /// </summary>
        internal static string SaveBMP_Description {
            get {
                return ResourceManager.GetString("SaveBMP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SavePath 的本地化字符串。
        /// </summary>
        internal static string SavePath {
            get {
                return ResourceManager.GetString("SavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Path 的本地化字符串。
        /// </summary>
        internal static string SavePath_Description {
            get {
                return ResourceManager.GetString("SavePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerActivation 的本地化字符串。
        /// </summary>
        internal static string TriggerActivation {
            get {
                return ResourceManager.GetString("TriggerActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerActivation：RisingEdge 的本地化字符串。
        /// </summary>
        internal static string TriggerActivation_Description {
            get {
                return ResourceManager.GetString("TriggerActivation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerMode 的本地化字符串。
        /// </summary>
        internal static string TriggerMode {
            get {
                return ResourceManager.GetString("TriggerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerMode ：ON/OFF 的本地化字符串。
        /// </summary>
        internal static string TriggerMode_Description {
            get {
                return ResourceManager.GetString("TriggerMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerSource 的本地化字符串。
        /// </summary>
        internal static string TriggerSource {
            get {
                return ResourceManager.GetString("TriggerSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TriggerSource：Software... 的本地化字符串。
        /// </summary>
        internal static string TriggerSource_Description {
            get {
                return ResourceManager.GetString("TriggerSource_Description", resourceCulture);
            }
        }
    }
}
